### ISSUE TITLE
when reLayout ui and the result is not change

### ISSUE THREAD

**Issue by brainsky** [Sleen/FlexLayout#3]
I want to relayout my ui, but the result is not change. Like this, first I set child1 height is 50, But when the context is too much, I will set child1 is 150. So I set Height is 150, I hope reLayout the root.  But is not change. code like as follows：
   FlexNodeRef root = Flex_newNode();
    Flex_setDirection(root, FlexVertical);
    FlexNodeRef child1 = Flex_newNode();
    Flex_setWidth(child1, 50);
    Flex_setHeight(child1, 50);
    Flex_addChild(root, child1);
    FlexNodeRef child2 = Flex_newNode();
    Flex_setWidth(child2, 50);
    Flex_setHeight(child2, 50);
    Flex_addChild(root, child2);
    Flex_layout(root, FlexUndefined, FlexUndefined, 1);
    // re-layout child1 
    Flex_setHeight(child1, 150);
    Flex_layout(root, FlexUndefined, FlexUndefined, 1);
    Flex_print(root, FlexPrintDefault);

   the running result in vscode like this:
   First printLayout:
   {
  direction: vertical
  result-width: 50.0
  result-height: 100.0
  children: [
    {
      width: 50.0
      height: 50.0
      result-width: 50.0
      result-height: 50.0
    }
    {
      width: 50.0
      height: 50.0
      result-y: 50.0
      result-width: 50.0
      result-height: 50.0
    }
  ]
}
Second printLayout:
{
  direction: vertical    
  result-width: 50.0     
  result-height: 100.0   
  children: [
    {
      width: 50.0        
      height: 150.0      
      result-width: 50.0 
      result-height: 50.0
    }
    {
      width: 50.0
      height: 50.0
      result-y: 50.0
      result-width: 50.0
      result-height: 50.0
    }
  ]
}
 Second layout child2 result-y is still 50, it should be 150. cause i change child1 height 150. I don't know how to do this, maybe is not use this method to relayout. Can u help me?

**Comment by brainsky** [comment]
flex_canUseCache method will be lead to not change

**Comment by Sleen** [comment]
I'm glad to receive feedback on the use of FlexLayout. It's not allowed to call `Flex_layout` twice on the same node tree, and if there are property changes you need to recreate the whole tree and call `Flex_layout` on the new root node (Thus layout caching is not supported). `flex_canUseCache` is only used to try to save time when traversing to the same node multiple times in a single layout.
